cargo-features = ["workspace-inheritance"]

[workspace]
members = [
	"src/mididump",
	"src/lsp",
	"src/fcon",
	"src/toysynth",
	"src/ksmp",
	"src/audiorec",
	"src/smprec",
	"src/midiuinput",
	"src/midifilter",
	"src/copypipe",
	"src/polysplit",
	"src/synthwidget",
	"src/usm",
]

[workspace.dependencies]
jack = "0.10"

[workspace.dependencies.aarg]
git = "https://github.com/asrcpq/aarg"
rev = "4ce9b93a80ea3d9e89c8ee205562a967b40a9dba"
